[package]
name = "main_package"
edition = "2024.beta"

[dependencies]
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "sui-contract-mainnet" }
deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "v3.0.0" }

[addresses]
main_package = "0x0"

[dev-dependencies]
# This dev dependencies point to the same versions as the main dependencies.
# Regardless whether they point to local dependencies, or remote dependencies (exact copies of main dependencies),
# or forked dependencies pointing to the different git repositories, 
# uncommenting them leads to the build failure.
# Same for the "override" flag (whether it is set to true or non-exists).

# Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "sui-contract-mainnet" }
# deepbook = { git = "https://github.com/MystenLabs/deepbookv3.git", subdir = "packages/deepbook", rev = "v3.0.0" }

[dev-addresses]
